# Generated by Django 2.2.5 on 2019-09-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=None)),
                ('file_name', models.CharField(max_length=200)),
            ],
        ),
    ]
